#!/bin/sh
export OSU_INSTALL_LOCATION="/mnt/ti/games/x86/osu-stable/"

mkdir -p "$HOME/.local/share/wineprefixes/"

export vblank_mode=0
export __GL_SYNC_TO_VBLANK=0

export WINEPREFIX="$HOME/.local/share/wineprefixes/osu-stable"
export WINEARCH=win32 

export STAGING_AUDIO_DURATION=20000
export STAGING_AUDIO_PERIOD=10000

export PATH="/opt/wine-osu/bin:$PATH"

if [ ! -f "$HOME/.local/share/applications/osu-stable.desktop" ]
then
    mkdir -p "$HOME/.local/share/icons/"
    mkdir -p "$HOME/.local/share/applications/"

    wget -O "$HOME/.local/share/icons/osu-stable.png" "https://i.imgur.com/Rswh32I.png"
    
    echo "[Desktop Entry]
          Type=Application
          Name=osu!
          Icon=osu-stable.png
          Exec=osu-stable %U
          Categories=Game;
          StartupWMClass=osu!.exe
          MimeType=x-scheme-handler/osu" > "$HOME/.local/share/applications/osu-stable.desktop"
fi

if [ ! -d "$OSU_INSTALL_LOCATION" ]
then
    mkdir -p $OSU_INSTALL_LOCATION
    wget -O "$OSU_INSTALL_LOCATION/osu!.exe" "https://m1.ppy.sh/r/osu!install.exe"
fi

if [ ! -d "$WINEPREFIX" ]
then
    winetricks -q dotnet40 gdiplus cjkfonts msxml3 msxml4 msxml6
fi

cd $OSU_INSTALL_LOCATION
wine "osu!.exe" "$@"
